server:
  name: web-api
  listener: 127.0.0.1:9090
  mode: debug
  timeout: 5
  enablePProf: false
  enableCron: false
  enableMetrics: true
  passEncryption: false

log:
  ServiceName: monitor-rpc
  Mode: console
  Encoding: plain
  Path: logs
  Level: debug
  Compress: true
  KeepDays: 3

registry:
  enable: false
  namespace: default
  endpoints:
  dialTimeout:
  ttl:
  maxRetry:

auth:
  jwtSecret: ASD111
  expire: 2000

rpcClient:
  endpoints:
    - 127.0.0.1:8082 #etcd?
  target: 127.0.0.1:8082
  app:
  token:
  nonBlock:
  timeout: 1000
